#!/usr/bin/env bash

# Install dependencies if not already installed
if [ ! -d dbt/dbt_packages ]; then
  dbt deps --project-dir=dbt
fi

# Run dbt models and analyses
dbt run --project-dir=dbt
dbt compile --project-dir=dbt

# Run the macro to export all analyses to CSV
chmod +x run_export
./run_export