#!/usr/bin/env bash

# Step 1: Run dbt models and analyses
dbt run --project-dir=dbt_project
dbt compile --project-dir=dbt_project

# Step 2: Run the macro to export all analyses to CSV
dbt run-operation export_all_analyses_to_csv --project-dir=dbt_project
